import { Vector2D } from '../../math/Vector2D';
import { AABB, createAABB } from '../../physics/AABB';
import { GameEngine, GameEntity } from '../../engine/GameEngine';
import { BossEntity, BossPhase } from './BossTypes';
import { TargetPlayer } from '../enemies/EnemyTypes';

/**
 * Destructible homing micro-missile fired by Tetsuyuki's dorsal rocket pods.
 * Tracks target player position with 2.2 rad/s max steering rate.
 * Has HP = 1, so a single player bullet destroys it in mid-air.
 */
export class TetsuyukiHomingMissile implements GameEntity {
  public id: string;
  public type: string = 'HOMING_MISSILE';
  public position: Vector2D;
  public velocity: Vector2D;
  public bounds: AABB;
  public isAlive: boolean = true;
  public health: number = 1;
  public headingAngle: number;
  public readonly speed: number = 175;
  public readonly maxSteerRate: number = 2.2; // 2.2 rad/s
  public blastRadius: number = 32;
  public damage: number = 2;
  private lifetime: number = 4.5;
  private targetPlayer: TargetPlayer | null = null;

  constructor(
    id: string,
    startPos: Vector2D,
    initialAngle: number = Math.PI,
    target: TargetPlayer | null = null
  ) {
    this.id = id;
    this.position = { x: startPos.x, y: startPos.y };
    this.headingAngle = initialAngle;
    this.velocity = {
      x: Math.cos(initialAngle) * this.speed,
      y: Math.sin(initialAngle) * this.speed,
    };
    this.bounds = createAABB(this.position.x, this.position.y, 10, 6);
    this.targetPlayer = target;
  }

  setTarget(target: TargetPlayer | null): void {
    this.targetPlayer = target;
  }

  takeDamage(amount: number): void {
    this.health -= amount;
    if (this.health <= 0) {
      this.health = 0;
      this.isAlive = false;
    }
  }

  update(dt: number, engine?: GameEngine): void {
    if (!this.isAlive) {
      if (engine) engine.removeEntity(this.id);
      return;
    }

    // Steering towards player target
    if (this.targetPlayer && this.targetPlayer.isAlive !== false) {
      const targetAngle = Math.atan2(
        this.targetPlayer.position.y - this.position.y,
        this.targetPlayer.position.x - this.position.x
      );

      let deltaAngle = Math.atan2(
        Math.sin(targetAngle - this.headingAngle),
        Math.cos(targetAngle - this.headingAngle)
      );

      const maxStep = this.maxSteerRate * dt;
      deltaAngle = Math.max(-maxStep, Math.min(maxStep, deltaAngle));
      this.headingAngle += deltaAngle;
    }

    this.velocity.x = Math.cos(this.headingAngle) * this.speed;
    this.velocity.y = Math.sin(this.headingAngle) * this.speed;

    this.position.x += this.velocity.x * dt;
    this.position.y += this.velocity.y * dt;
    this.bounds.x = this.position.x;
    this.bounds.y = this.position.y;

    this.lifetime -= dt;
    if (this.lifetime <= 0) {
      this.detonate(engine);
    }
  }

  detonate(engine?: GameEngine): void {
    if (!this.isAlive) return;
    this.isAlive = false;

    if (engine) {
      engine.eventBus.emit('explosion_spawned', {
        position: { x: this.position.x, y: this.position.y },
        radius: this.blastRadius,
        damage: this.damage,
      });
      engine.removeEntity(this.id);
    }
  }
}

/**
 * Traveling ground shockwave generated by Tetsuyuki's emergency thrusters.
 */
export class TetsuyukiShockwave implements GameEntity {
  public id: string;
  public type: string = 'THRUSTER_SHOCKWAVE';
  public position: Vector2D;
  public velocity: Vector2D;
  public bounds: AABB;
  public isAlive: boolean = true;
  public damage: number = 2;
  private lifetime: number = 2.8;

  constructor(id: string, startPos: Vector2D, speedX: number = -180) {
    this.id = id;
    this.position = { x: startPos.x, y: startPos.y };
    this.velocity = { x: speedX, y: 0 };
    this.bounds = createAABB(this.position.x, this.position.y, 28, 20);
  }

  update(dt: number, engine?: GameEngine): void {
    if (!this.isAlive) return;
    this.position.x += this.velocity.x * dt;
    this.bounds.x = this.position.x;

    this.lifetime -= dt;
    if (this.lifetime <= 0) {
      this.isAlive = false;
      if (engine) engine.removeEntity(this.id);
    }
  }
}

/**
 * Heavy artillery shell fired by Tetsuyuki underside swivel cannon.
 */
export class TetsuyukiArtilleryShell implements GameEntity {
  public id: string;
  public type: string = 'ARTILLERY_SHELL';
  public position: Vector2D;
  public velocity: Vector2D;
  public bounds: AABB;
  public isAlive: boolean = true;
  public blastRadius: number = 80;
  public damage: number = 4;
  private lifetime: number = 3.0;

  constructor(id: string, startPos: Vector2D, speedX: number = -360) {
    this.id = id;
    this.position = { x: startPos.x, y: startPos.y };
    this.velocity = { x: speedX, y: 0 };
    this.bounds = createAABB(this.position.x, this.position.y, 16, 12);
  }

  update(dt: number, engine?: GameEngine): void {
    if (!this.isAlive) return;
    this.position.x += this.velocity.x * dt;
    this.bounds.x = this.position.x;

    this.lifetime -= dt;
    if (this.lifetime <= 0) {
      this.detonate(engine);
    }
  }

  detonate(engine?: GameEngine): void {
    if (!this.isAlive) return;
    this.isAlive = false;
    if (engine) {
      engine.eventBus.emit('explosion_spawned', {
        position: { x: this.position.x, y: this.position.y },
        radius: this.blastRadius,
        damage: this.damage,
      });
      engine.removeEntity(this.id);
    }
  }
}

export interface TetsuyukiConfig {
  customHp?: number;
  initialPhase?: BossPhase;
}

/**
 * Stage 1 End-Boss: Tetsuyuki War Fortress
 * Multi-phase state machine with damage-gated transitions:
 * - PHASE_1_ARTILLERY: Dual heavy cannon barrage and homing rocket pods.
 * - PHASE_2_LASER_SWEEP: Hull breach, engine overheat, thermal laser sweep across battlefield, rapid gatling turret.
 * - PHASE_3_MELTDOWN: Emergency thruster shockwaves, exposed reactor core weak-point (48x48 px, takes 1.5x damage).
 * - DEATH_EXPLODING: 4-stage timed chain explosion sequence (3.2 seconds) transitioning to DESTROYED.
 */
export class TetsuyukiBoss implements BossEntity, GameEntity {
  public readonly id: string;
  public readonly type: string = 'BOSS_TETSUYUKI';
  public position: Vector2D;
  public velocity: Vector2D = { x: 0, y: 0 };
  public health: number;
  public maxHealth: number = 400;
  public phase: BossPhase = 'PHASE_1_ARTILLERY';
  public isAlive: boolean = true;
  public isMeleeVulnerable: boolean = false;
  public turretsAlive: number = 2;
  public weakPointExposed: boolean = false;

  // Boss dimensions
  public readonly width: number = 280;
  public readonly height: number = 160;
  public bounds: AABB;

  get boundingBox(): AABB {
    return this.bounds;
  }

  // 48x48 exposed reactor core weak point
  public weakPointBox: AABB;

  // Phase 1 Attack State
  private artilleryCooldownTimer: number = 3.5;
  private isArtilleryCharging: boolean = false;
  private missileSalvoTimer: number = 4.0;
  private missileBurstCount: number = 0;
  private missileBurstInterval: number = 0;
  public activeMissiles: TetsuyukiHomingMissile[] = [];
  public spawnedArtilleryShells: TetsuyukiArtilleryShell[] = [];
  public spawnedShockwaves: TetsuyukiShockwave[] = [];

  // Phase 2 Attack State
  public isHullBreached: boolean = false;
  public isLaserWarning: boolean = false;
  public isLaserActive: boolean = false;
  public laserSweepProgress: number = 0; // 0.0 to 1.0
  public laserFloorHitbox: AABB | null = null;
  private laserCycleTimer: number = 2.0;
  private gatlingFireTimer: number = 0;
  private debrisSpawnTimer: number = 1.5;

  // Phase 3 Attack State
  private thrusterShockwaveTimer: number = 2.5;
  private fanRocketTimer: number = 3.8;

  // Death Exploding Sequence State
  public deathTimer: number = 0;
  public deathStage: number = 0; // 1, 2, 3, 4
  public screenShakeOffset: number = 0;

  // Target Player Reference
  private targetPlayer: TargetPlayer | null = null;

  constructor(
    id: string,
    initialPosition: Vector2D = { x: 360, y: 50 },
    config: TetsuyukiConfig = {}
  ) {
    this.id = id;
    this.position = { x: initialPosition.x, y: initialPosition.y };
    this.maxHealth = config.customHp ?? 400;
    this.health = this.maxHealth;
    this.phase = config.initialPhase ?? 'PHASE_1_ARTILLERY';

    this.bounds = createAABB(this.position.x, this.position.y, this.width, this.height);

    // 48x48 weak point placed at reactor center
    this.weakPointBox = createAABB(
      this.position.x + 60,
      this.position.y + 40,
      48,
      48
    );
  }

  setTargetPlayer(target: TargetPlayer | null): void {
    this.targetPlayer = target;
  }

  getArtilleryMuzzle(): Vector2D {
    return {
      x: this.position.x + 10,
      y: this.position.y + this.height - 24,
    };
  }

  getDorsalPodPosition(): Vector2D {
    return {
      x: this.position.x + 80,
      y: this.position.y + 10,
    };
  }

  getReactorCoreCenter(): Vector2D {
    return {
      x: this.weakPointBox.x + this.weakPointBox.width / 2,
      y: this.weakPointBox.y + this.weakPointBox.height / 2,
    };
  }

  update(dt: number, engine?: GameEngine): void {
    if (this.phase === 'DESTROYED') return;

    // Clean inactive homing missiles
    this.activeMissiles = this.activeMissiles.filter((m) => m.isAlive);

    // Resolve target player from engine if needed
    if (!this.targetPlayer && engine) {
      const playerEntity = engine.getEntity('player');
      if (playerEntity && playerEntity.isAlive) {
        this.targetPlayer = {
          position: playerEntity.position,
          bounds: playerEntity.bounds,
          isAlive: playerEntity.isAlive,
        };
      }
    }

    // Update weak point box position with boss position
    this.weakPointBox.x = this.position.x + 60;
    this.weakPointBox.y = this.position.y + 40;

    // State Machine execution
    switch (this.phase) {
      case 'PHASE_1_ARTILLERY':
        this.updatePhase1(dt, engine);
        break;
      case 'PHASE_2_LASER_SWEEP':
        this.updatePhase2(dt, engine);
        break;
      case 'PHASE_3_MELTDOWN':
        this.updatePhase3(dt, engine);
        break;
      case 'DEATH_EXPLODING':
        this.updateDeathExploding(dt, engine);
        break;
    }

    // Synchronize bounding box
    this.bounds.x = this.position.x;
    this.bounds.y = this.position.y;
  }

  // =========================================================================
  // PHASE 1: Dual Heavy Artillery Cannon Barrage & Guided Homing Rocket Pods
  // (100% -> 65% HP: 400 -> 260 HP)
  // =========================================================================
  private updatePhase1(dt: number, engine?: GameEngine): void {
    this.weakPointExposed = false;

    // 1. Heavy Artillery Cannon Cycle
    this.artilleryCooldownTimer -= dt;
    if (this.artilleryCooldownTimer <= 1.0 && !this.isArtilleryCharging) {
      this.isArtilleryCharging = true;
      if (engine) {
        engine.eventBus.emit('artillery_charging', {
          position: this.getArtilleryMuzzle(),
          duration: 1.0,
        });
      }
    }

    if (this.artilleryCooldownTimer <= 0) {
      this.fireArtilleryShell(engine);
      this.isArtilleryCharging = false;
      this.artilleryCooldownTimer = 4.0;
    }

    // 2. Guided Rocket Pod Salvo (Salvo of 3 missiles)
    this.missileSalvoTimer -= dt;
    if (this.missileSalvoTimer <= 0) {
      this.missileBurstCount = 3;
      this.missileBurstInterval = 0;
      this.missileSalvoTimer = 5.5;
    }

    if (this.missileBurstCount > 0) {
      this.missileBurstInterval -= dt;
      if (this.missileBurstInterval <= 0) {
        this.fireHomingMissile(engine);
        this.missileBurstCount--;
        this.missileBurstInterval = 0.2; // 200ms interval
      }
    }
  }

  private fireArtilleryShell(engine?: GameEngine): void {
    const muzzle = this.getArtilleryMuzzle();
    const shell = new TetsuyukiArtilleryShell(
      `artillery_${this.id}_${Date.now()}_${Math.random()}`,
      muzzle,
      -360 // Horizontal speed -360 px/s
    );

    this.spawnedArtilleryShells.push(shell);

    if (engine) {
      engine.addEntity(shell);
      engine.eventBus.emit('artillery_fired', {
        position: muzzle,
        shellId: shell.id,
      });
    }
  }

  private fireHomingMissile(engine?: GameEngine): void {
    const podPos = this.getDorsalPodPosition();
    const missile = new TetsuyukiHomingMissile(
      `missile_${this.id}_${Date.now()}_${Math.random()}`,
      podPos,
      Math.PI * 0.85, // Initial launch trajectory
      this.targetPlayer
    );

    this.activeMissiles.push(missile);

    if (engine) {
      engine.addEntity(missile);
      engine.eventBus.emit('rocket_launched', {
        position: podPos,
        missileId: missile.id,
      });
    }
  }

  // =========================================================================
  // PHASE 2: Hull Breach, Thermal Laser Sweep, Rapid Gatling Turret
  // (65% -> 30% HP: 260 -> 120 HP)
  // =========================================================================
  private updatePhase2(dt: number, engine?: GameEngine): void {
    this.isHullBreached = true;
    this.weakPointExposed = false;

    // 1. Thermal Laser Sweep Cycle
    this.laserCycleTimer -= dt;

    if (this.laserCycleTimer <= 0.8 && this.laserCycleTimer > 0) {
      // 0.8s warning telegraph
      this.isLaserWarning = true;
      this.isLaserActive = false;
      this.laserFloorHitbox = null;
      if (engine) {
        engine.eventBus.emit('laser_warning', { floorY: 220 });
      }
    } else if (this.laserCycleTimer <= 0 && this.laserCycleTimer > -1.5) {
      // 1.5s active sweep across floor
      this.isLaserWarning = false;
      this.isLaserActive = true;
      const progress = Math.abs(this.laserCycleTimer) / 1.5;
      this.laserSweepProgress = progress;

      // Sweeping floor hitbox moving from right (480) to left (0)
      const sweepX = 480 - progress * 480;
      this.laserFloorHitbox = createAABB(sweepX - 20, 210, 40, 20);

      if (engine) {
        engine.eventBus.emit('laser_sweeping', {
          sweepX,
          hitbox: this.laserFloorHitbox,
        });
      }
    } else if (this.laserCycleTimer <= -1.5) {
      // Laser cycle finished, reset for next sweep
      this.isLaserWarning = false;
      this.isLaserActive = false;
      this.laserFloorHitbox = null;
      this.laserCycleTimer = 3.5;
    }

    // 2. Rapid Gatling Rotary Gun (10 rounds/s in downward cone)
    this.gatlingFireTimer -= dt;
    if (this.gatlingFireTimer <= 0) {
      this.gatlingFireTimer = 0.1; // 100ms = 10 rounds/sec
      if (engine) {
        const spreadAngle = -Math.PI / 4 + (Math.random() - 0.5) * 0.25;
        engine.eventBus.emit('gatling_tracer', {
          origin: { x: this.position.x + 20, y: this.position.y + 70 },
          angle: spreadAngle,
        });
      }
    }

    // 3. Falling Structural Debris
    this.debrisSpawnTimer -= dt;
    if (this.debrisSpawnTimer <= 0) {
      this.debrisSpawnTimer = 2.0;
      if (engine) {
        engine.eventBus.emit('falling_debris', {
          x: 60 + Math.random() * 400,
          y: 0,
          vy: 320,
        });
      }
    }
  }

  // =========================================================================
  // PHASE 3: Emergency Thruster Meltdown, Exposed Weak Point, Fan Rockets
  // (30% -> 0% HP: 120 -> 0 HP)
  // =========================================================================
  private updatePhase3(dt: number, engine?: GameEngine): void {
    this.weakPointExposed = true;
    this.isLaserWarning = false;
    this.isLaserActive = false;
    this.laserFloorHitbox = null;

    // 1. Emergency Thruster Shockwave Attacks
    this.thrusterShockwaveTimer -= dt;
    if (this.thrusterShockwaveTimer <= 0) {
      this.spawnThrusterShockwave(engine);
      this.thrusterShockwaveTimer = 3.0;
    }

    // 2. 5-Way Fan Spread Rocket Barrage
    this.fanRocketTimer -= dt;
    if (this.fanRocketTimer <= 0) {
      this.fireFanRocketBarrage(engine);
      this.fanRocketTimer = 4.2;
    }
  }

  private spawnThrusterShockwave(engine?: GameEngine): void {
    const shockwaveOrigin: Vector2D = {
      x: this.position.x + 20,
      y: 210, // Ground level
    };

    const shockwave = new TetsuyukiShockwave(
      `shockwave_${this.id}_${Date.now()}_${Math.random()}`,
      shockwaveOrigin,
      -180 // Traveling left at 180 px/s
    );

    this.spawnedShockwaves.push(shockwave);

    if (engine) {
      engine.addEntity(shockwave);
      engine.eventBus.emit('shockwave_spawned', {
        position: shockwaveOrigin,
        speed: -180,
      });
    }
  }

  private fireFanRocketBarrage(engine?: GameEngine): void {
    const anglesDeg = [150, 165, 180, 195, 210];
    const podPos = this.getDorsalPodPosition();

    for (const deg of anglesDeg) {
      const rad = (deg * Math.PI) / 180;
      const vel: Vector2D = {
        x: Math.cos(rad) * 240,
        y: Math.sin(rad) * 240,
      };

      if (engine) {
        engine.eventBus.emit('fan_rocket_fired', {
          origin: podPos,
          velocity: vel,
          angle: rad,
        });
      }
    }
  }

  // =========================================================================
  // DEATH EXPLODING: 4-Stage Timed Chain Explosion Sequence (3.2 seconds)
  // transitioning to DESTROYED
  // =========================================================================
  private updateDeathExploding(dt: number, engine?: GameEngine): void {
    this.deathTimer += dt;
    this.velocity = { x: 0, y: 0 };

    // Stage 1: 0.0s - 0.8s: Localized small sparks across wings and hull
    if (this.deathTimer < 0.8) {
      this.deathStage = 1;
      this.screenShakeOffset = 0;
      if (engine) {
        engine.eventBus.emit('boss_spark_explosion', {
          position: {
            x: this.position.x + Math.random() * this.width,
            y: this.position.y + Math.random() * this.height,
          },
          radius: 16,
        });
      }
    }
    // Stage 2: 0.8s - 2.0s: Armor tear fireballs + camera screen shake
    else if (this.deathTimer >= 0.8 && this.deathTimer < 2.0) {
      this.deathStage = 2;
      const t = this.deathTimer;
      this.screenShakeOffset = 6 * Math.sin(50 * t) * Math.exp(-0.5 * t);

      if (engine) {
        engine.eventBus.emit('boss_armor_explosion', {
          position: {
            x: this.position.x + Math.random() * this.width,
            y: this.position.y + Math.random() * this.height,
          },
          radius: 40,
          screenShake: this.screenShakeOffset,
        });
      }
    }
    // Stage 3: 2.0s - 3.2s: Core reactor detonation, white flash, shockwave
    else if (this.deathTimer >= 2.0 && this.deathTimer < 3.2) {
      this.deathStage = 3;
      const coreCenter = this.getReactorCoreCenter();
      const waveRadius = 150 * ((this.deathTimer - 2.0) / 1.2);

      if (engine) {
        engine.eventBus.emit('boss_core_detonation', {
          coreCenter,
          waveRadius,
          flashWhite: true,
        });
      }
    }
    // Stage 4: t >= 3.2s: Transitions to DESTROYED
    else if (this.deathTimer >= 3.2) {
      this.deathStage = 4;
      this.phase = 'DESTROYED';
      this.isAlive = false;

      if (engine) {
        engine.eventBus.emit('boss_destroyed', {
          id: this.id,
          wreckagePosition: this.position,
        });
        engine.eventBus.emit('mission_complete', {
          score: 10000,
        });
      }
    }
  }

  public transitionToPhase2(): void {
    this.phase = 'PHASE_2_LASER_SWEEP';
    this.turretsAlive = 1;
    this.laserCycleTimer = 1.5;
    this.isHullBreached = true;
  }

  public transitionToPhase3(): void {
    this.phase = 'PHASE_3_MELTDOWN';
    this.turretsAlive = 0;
    this.weakPointExposed = true;
    this.isHullBreached = true;
  }

  public transitionToDeath(): void {
    this.health = 0;
    this.phase = 'DEATH_EXPLODING';
    this.deathTimer = 0;
    this.deathStage = 1;
    this.weakPointExposed = false;
    this.isHullBreached = true;
  }

  /**
   * Evaluates damage with multi-phase transitions and weak-point scaling.
   * Dynamic thresholds:
   * - Phase 1 -> Phase 2 at 65% maxHealth (e.g. 260 HP for 400 maxHealth).
   * - Phase 2 -> Phase 3 at 30% maxHealth (e.g. 120 HP for 400 maxHealth).
   * - Phase 3 -> Death at 0 HP.
   * Phase 3:
   * - Hits to exposed core take 1.5x damage.
   * - Hits to armored superstructure take 0.25x damage (75% armor reduction).
   */
  takeDamage(amount: number, isWeakPoint: boolean = false): void {
    if (!this.isAlive || this.phase === 'DEATH_EXPLODING' || this.phase === 'DESTROYED') {
      return;
    }

    let effectiveDamage = amount;

    if (this.phase === 'PHASE_3_MELTDOWN') {
      if (isWeakPoint) {
        effectiveDamage = amount * 1.5;
      } else {
        effectiveDamage = amount * 0.25;
      }
    }

    const p1Threshold = Math.round(this.maxHealth * 0.65);
    const p2Threshold = Math.round(this.maxHealth * 0.30);

    if (this.phase === 'PHASE_1_ARTILLERY') {
      this.health = Math.max(p1Threshold, this.health - effectiveDamage);
      if (this.health <= p1Threshold) {
        this.transitionToPhase2();
      }
      return;
    }

    if (this.phase === 'PHASE_2_LASER_SWEEP') {
      this.health = Math.max(p2Threshold, this.health - effectiveDamage);
      if (this.health <= p2Threshold) {
        this.transitionToPhase3();
      }
      return;
    }

    if (this.phase === 'PHASE_3_MELTDOWN') {
      this.health = Math.max(0, this.health - effectiveDamage);
      if (this.health <= 0) {
        this.transitionToDeath();
      }
      return;
    }
  }
}
